import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >

          <div className="bg-background">
            <div className="flex w-full min-h-screen">
              <Sidebar className="w-[300px] hidden lg:block border-r" />
              <div className="p-5 mx-auto w-[1300px]">{children}</div>
            </div>
          </div>

        </ThemeProvider>
      </body>
    </html>
  );
}
